name: Build Main Branch

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: value

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Scan de secrets
        run: |
          echo "Todo : Scan de secrets"
        shell: bash

      - name: Scan des vulnérabilités
        run: |
          echo "Todo : Scan des vulnérabilités"
        shell: bash

      - name: Unit Tests
        run: |
          mvn test -Put -Pit
        shell: bash

      - name: Quality Gate
        run: |
          echo "Todo : Quality Gate"
        shell: bash

      - name: Check Quality Gate
        run: |
          echo "Todo : Check Quality Gate"
        shell: bash

      - name: Release
        run: |
          echo "Todo : Release"
        shell: bash

      - name: Build and Publish to Docker
        run: |
          echo "Todo : Build and Publish to Docker"
        shell: bash

      - name: Déploiement
        run: |
          echo "Todo : Déploiement "
        shell: bash

      - name: DAST
        run: |
          echo "Todo : DAST"
        shell: bash