name: Pull Request
on:
  push:
    branches:
      - 'DIC1-*'
      - 'IS-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: value

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Scan de secrets
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
       

      - name: Scan des vulnérabilités
        # Cette étape analyse les bibliothèques Java (pom.xml) pour détecter les vulnérabilités (CVEs)
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'MyJavaProject'
          path: '.'
          format: 'ALL'
          args: >
            --enableRetired
            --enableExperimental
            --failOnCVSS 7
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --nvdApiDelay 2000
            --nvdValidForHours 24
            --out reports
            --scan "**/*.jar"
            --scan "**/pom.xml"
            --exclude "**/target/**"
            --exclude "**/test/**"
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-check-report
          path: reports/
          retention-days: 30

      
      - name: Unit Tests
        run: |
          mvn test -Put -Pit
        shell: bash

      - name: Quality Gate
        run: |
          echo "Todo : Quality Gate"
        shell: bash

      - name: Check Quality Gate
        run: |
          echo "Todo : Check Quality Gate"
        shell: bash

