name: Pull Request
on:
  push:
    branches:
      - 'DIC1-*'
      - 'IS-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: value

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Scan de secrets
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: Scan des vulnérabilités via Docker
        run: |
          docker run --rm \
            -v $(pwd):/src \
            owasp/dependency-check \
            --project "pull-request-scan" \
            --scan /src \
            --format "JSON,XML" \
            --out /src/reports \
            --nvdApiKey "${{ secrets.NVD_API_KEY }}" \
            --nvdApiDelay 2000 \
            --nvdValidForHours 24 \
            --failOnCVSS 7 \
            --enableRetired \
            --enableExperimental \
            --exclude "**/target/**" \
            --exclude "**/test/**"


      # - name: Scan des vulnérabilités
      #   uses: dependency-check/Dependency-Check_Action@main
      #   with: 
      #     project: "pull-request-scan"
      #     path: "."
      #     format: "JSON,XML"
      #     args: >
      #       --nvdApiKey ${{ secrets.NVD_API_KEY }}
      #       --nvdApiDelay 2000
      #       --nvdValidForHours 24
      #       --failOnCVSS 7
      #       --enableRetired
      #       --enableExperimental
      #       --exclude "**/target/**"
      #       --exclude "**/test/**"
      
      - name: Unit Tests
        run: |
          mvn test -Put -Pit
        shell: bash

      - name: Quality Gate
        run: |
          echo "Todo : Quality Gate"
        shell: bash

      - name: Check Quality Gate
        run: |
          echo "Todo : Check Quality Gate"
        shell: bash