name: Pull Request
on:
  push:
    branches:
      - 'DIC1-*'
      - 'IS-*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: value

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Scan de secrets
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
       

      - name: Scan des vulnérabilités
  # Cette étape analyse les bibliothèques Java (pom.xml) pour détecter les vulnérabilités (CVEs)
        uses: dependency-check/Dependency-Check_Action@main
        with: 
          project: "pull-request-scan"
          path: "."
          format: "JSON,XML"
          failOnCVSS: 7.0
      
      - name: Unit Tests
        run: |
          mvn test -Put -Pit
        shell: bash

      - name: Quality Gate
        run: |
          echo "Todo : Quality Gate"
        shell: bash

      - name: Check Quality Gate
        run: |
          echo "Todo : Check Quality Gate"
        shell: bash

